name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - LICENSE
      - docs/**
      - .github/**
      - .gitignore

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - uses: gradle/gradle-build-action@v2
