name: Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 17
        
      - name: Gradle setup
        uses: gradle/gradle-build-action@v2

      - name: Gradle build
        run: ./gradlew build
          
      - name: Publish to CurseForge
        env:
          CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
        run: ./gradlew curseforge
